# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newspaper', '0003_auto_20171206_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
