# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newspaper', '0004_auto_20171206_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
    ]
